# Generated by Django 5.1.3 on 2024-11-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='col',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='row',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='one', max_length=16),
        ),
    ]
