# Generated by Django 5.1.3 on 2024-11-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_tile_rename_col_player_score_remove_player_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='player', max_length=16),
        ),
    ]
