# Generated by Django 5.1.3 on 2024-11-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='tag',
        ),
        migrations.AlterField(
            model_name='tile',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
